export const CITY_OPTIONS = [
  "Chicago, IL", "New York, NY", "Austin, TX", "San Francisco, CA",
  "Seattle, WA", "Los Angeles, CA", "Boston, MA", "Denver, CO",
];

export const US_STATE_OPTIONS = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
  "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
  "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
  "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
  "New Hampshire", "New Jersey", "New Mexico", "New York",
  "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
  "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
  "West Virginia", "Wisconsin", "Wyoming",
];

export const SCHOOL_OPTIONS = [
  // Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "Cornell University",
  // Top Business / Finance Programs
  "University of Chicago (Booth)",
  "Northwestern University (Kellogg)",
  "New York University (Stern)",
  "University of Michigan (Ross)",
  "University of Virginia (McIntire)",
  "Georgetown University (McDonough)",
  "University of Notre Dame (Mendoza)",
  "Emory University (Goizueta)",
  "Vanderbilt University (Owen)",
  "Washington University in St. Louis (Olin)",
  "Boston College (Carroll)",
  "Indiana University (Kelley)",
  "University of Illinois Urbana-Champaign (Gies)",
  "University of Texas at Austin (McCombs)",
  "University of North Carolina at Chapel Hill (Kenan-Flagler)",
  "Ohio State University (Fisher)",
  "University of Southern California (Marshall)",
  "Carnegie Mellon University (Tepper)",
  "Georgia Institute of Technology (Scheller)",
  "University of Wisconsin-Madison (Wisconsin School of Business)",
  "Penn State University (Smeal)",
  "Michigan State University (Broad)",
  "University of Minnesota (Carlson)",
  "University of Florida (Warrington)",
  "University of Maryland (Smith)",
  "University of Georgia (Terry)",
  "Purdue University (Krannert)",
  "Arizona State University (Carey)",
  // Elite Liberal Arts
  "Amherst College",
  "Williams College",
  "Middlebury College",
  "Colgate University",
  "Hamilton College",
  "Colby College",
  "Bowdoin College",
  "Swarthmore College",
  "Haverford College",
  "Wellesley College",
  "Smith College",
  "Vassar College",
  "Wesleyan University",
  "Trinity College",
  "Bucknell University",
  "Lafayette College",
  "Lehigh University",
  "Villanova University",
  "Fordham University",
  "Boston University",
  "Tufts University",
  "Wake Forest University",
  "College of William & Mary",
  "University of Richmond",
  "Babson College",
  // Large State Universities
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of Washington",
  "University of Colorado Boulder",
  "University of Arizona",
  "University of Oregon",
  "University of Utah",
  "University of Iowa",
  "University of Kansas",
  "University of Missouri",
  "University of Nebraska-Lincoln",
  "University of Oklahoma",
  "University of Arkansas",
  "University of Alabama",
  "Auburn University",
  "University of Tennessee",
  "University of South Carolina",
  "University of Kentucky",
  "University of Pittsburgh",
  "Temple University",
  "Rutgers University",
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "University of New Hampshire",
  "University of Vermont",
  "Syracuse University",
  "Northeastern University",
  "George Washington University",
  "American University",
  "Howard University",
  "Johns Hopkins University",
  "Duke University",
  "Rice University",
  "Tulane University",
  "Case Western Reserve University",
  "Southern Methodist University",
  "Texas A&M University",
  "University of Houston",
  "Baylor University",
  "Texas Christian University",
  "University of Denver",
  "Loyola University Chicago",
  "DePaul University",
  "University of Illinois Chicago",
  // HBCUs
  "Morehouse College",
  "Spelman College",
  "Howard University",
  "Hampton University",
  "Fisk University",
  "Clark Atlanta University",
  "Florida A&M University",
  "North Carolina A&T State University",
  "Prairie View A&M University",
  "Xavier University of Louisiana",
  "Morgan State University",
  "Lincoln University",
  "Tuskegee University",
  "Delaware State University",
  "Bowie State University",
  // Military Academies
  "United States Military Academy (West Point)",
  "United States Naval Academy",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  // International (common feeders to US finance)
  "London School of Economics",
  "University of Oxford",
  "University of Cambridge",
  "McGill University",
  "University of Toronto",
  "University of Hong Kong",
  "National University of Singapore",
];

export const DEGREE_OPTIONS = [
  "Bachelor of Arts (B.A.)",
  "Bachelor of Science (B.S.)",
  "Bachelor of Business Administration (B.B.A.)",
  "Bachelor of Fine Arts (B.F.A.)",
  "Bachelor of Engineering (B.E.)",
  "Associate of Arts (A.A.)",
  "Associate of Science (A.S.)",
  "Associate of Applied Science (A.A.S.)",
  "Master of Arts (M.A.)",
  "Master of Science (M.S.)",
  "Master of Business Administration (M.B.A.)",
  "Master of Fine Arts (M.F.A.)",
  "Master of Public Administration (M.P.A.)",
  "Master of Public Health (M.P.H.)",
  "Master of Education (M.Ed.)",
  "Master of Engineering (M.Eng.)",
  "Master of Finance (M.Fin.)",
  "Doctor of Philosophy (Ph.D.)",
  "Juris Doctor (J.D.)",
  "Doctor of Medicine (M.D.)",
  "Doctor of Business Administration (D.B.A.)",
];

export const SKILL_OPTIONS = [
  "TypeScript", "React", "Next.js", "Node.js", "PostgreSQL",
  "Prisma", "Tailwind CSS", "Python", "AWS", "Docker",
];
